AIRPORTS = {
    "RUH": "King Khalid International Airport, Riyadh, Saudi Arabia",
    "JED": "King Abdulaziz International Airport, Jeddah, Saudi Arabia",
    "DMM": "King Fahd International Airport, Dammam, Saudi Arabia",
    "MED": "Prince Mohammad bin Abdulaziz International Airport, Medina, Saudi Arabia",
    "TIF": "Taif Regional Airport, Taif, Saudi Arabia",
    "AHB": "Abha International Airport, Abha, Saudi Arabia",
    "ELQ": "Prince Nayef bin Abdulaziz Regional Airport, Buraidah, Saudi Arabia",
    "YNB": "Yanbu Airport, Yanbu, Saudi Arabia",
    "HAS": "Ha'il Regional Airport, Ha'il, Saudi Arabia",
    "EAM": "Najran Domestic Airport, Najran, Saudi Arabia",
    "AQI": "Al Qaisumah/Hafr Al Batin Airport, Hafr Al Batin, Saudi Arabia",
    "GIZ": "Jizan Regional Airport, Jizan, Saudi Arabia",
    "ULH": "Prince Abdul Majeed bin Abdulaziz Domestic Airport, Al-Ula, Saudi Arabia",
    "URY": "Guriat Domestic Airport, Gurayat, Saudi Arabia",
    "TUU": "Tabuk Regional Airport, Tabuk, Saudi Arabia",
    "WAE": "Wadi Al Dawasir Domestic Airport, Wadi ad-Dawasir, Saudi Arabia",
    "RAE": "Arar Domestic Airport, Arar, Saudi Arabia",
    "DWD": "Dawadmi Domestic Airport, Dawadmi, Saudi Arabia",
}
